### ISSUE TITLE
CLDR

### ISSUE THREAD

**Issue by layik** [layik/kurdi#14]
kake @jwtiyar, my [understanding](https://github.com/unicode-org/cldr/pull/823) was that:

1. you were trying to change some characters on Kurdi
2. you sent a PR on a file called X
3. they asked you to send the PR on file called Y

Why should we not just send the PR on file called Y?

Supas kake gyan.

**Comment by jwtiyar** [comment]
دەستەکانت خۆش، ڕاستە ئێستا کیشەکە وای لێ هاتووە چونکە نایانەوێ بیگۆڕن، من ویستم ئەو ku_arab بگۆڕم بۆ ckb
 ئەگەر نا دەمزانی کە دووانی جیاوازن.
ئەم ماوەیە زۆر ناتوانم لە سەر کۆمپیوتەر بمێنمەوە ئەگەر خۆت کاتت هەبوو دانەیەکی نوێیان بۆ بنێرە.

سوپاس

**Comment by layik** [comment]
دەی باشە کاکۆ گیان. مادەم ئامانجەکە (١)ە، با سەرئێشەیان بۆ دروست نەکەین.

**Comment by layik** [comment]
unicode-org/cldr/pull/2412

**Comment by layik** [comment]
Merged
سوپاس بۆ تۆش کاکە جووتیار
