### ISSUE TITLE
کام هەنگاوانە بنرێت بۆ یەکخستنی زمانی کوردی

### ISSUE THREAD

**Issue by layik** [layik/kurdi#15]
گریمان کەسێک سەرپشکی کردوویت لەوەی سێ هەنگاو بنێیت بۆ یەکخستنی نووسینی زمانی کوردی بە هەردوو شێوەی ئارامی و لاتینی. ئەو هەنگاوانە چی بن؟

<div dir="rtl">

- [ ] بەردەستخستن و یەکخستنی تەختەکلیلەکانی سیستمە جیاوازەکان بە هەردوو پیتی ئارامی و لاتینی (لینوکس، ماک، ویندۆز، ئاندرۆید و ئای ئۆ ئێس هتد)
- [ ] بەردەستخستنی یەک فەرهەنگی گشتگیر بۆ هەردوو زاراوە سەرەکیەکە بە هەردوو پیتی لاتینی و ئارامی
- [ ] بەردەستخستنی (دوای پەرەپێدان) هەڵەبژێر/هەڵەچن بۆ سیستمە جیاوازەکان بۆ ڕێگرتن لە هەڵە نووسین
- [ ] چی تر؟

سوپاس

**Comment by petrichor-494** [comment]
ڕێکخستنی ڕێنووسی کوردی.

**Comment by rojvv** [comment]
دەبێت بە شێوەیەکی سیستەماتیک کار بۆ ئەوە بکرێت هەموو کەسێک ئاشنا بکرێت بەو یاسایانەی کە کۆڕی زانیاریی کورد دایناون بۆ ڕاستنووسین. بە شێوەیەکیش کە یەکێک ڕێزمان نەزانێت لێی تێبگات.

**Comment by layik** [comment]
سوپاس. هەموویان لە پشت ئامێرەوەن. چ ئامرازێک پێویستە یان باشترین گۆڕانکاری دەکات. بیر لە فلتەر دانان لەسەر input بکەرەوە. ئەوەیان دەرەوەی کاری ئێمەیە.

**Comment by layik** [comment]
سوپاس کاکە @roj1512 دای دەخەم تا کاتێکی تر.
