### ISSUE TITLE
Android Kurdi

### ISSUE THREAD

**Issue by layik** [layik/kurdi#6]
- [x] Find out if there is CKB locale, my understanding is that there was as far back as 5.0?
- [x] Where are the locale?
- [ ] Where is the equivalent of [this](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/commit/645a00f4e106c5ac012a8139cc7f3a01d0aa1b1b#1e15a75cc541ddc8c0537ca912a79a0f260e085d)?

**Comment by 0xdolan** [comment]
check out this! I think this one is better (or has better support let's say) than SwiftKey.
https://play.google.com/store/apps/details?id=com.boloorian.android.kurdishkeyboard

**Comment by layik** [comment]
Supas kake Dolan gyan, let us focus on the issue. I can build one myself, I am done with these things.

**Comment by 0xdolan** [comment]
Definitely, I am sure. Just wanted to give a clue maybe SwiftKey used the same with some changes!

**Comment by layik** [comment]
```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Locale[] locales = Locale.getAvailableLocales();
        ArrayList<String> localcountries=new ArrayList<String>();
        for(Locale l:locales)
        {
            localcountries.add(l.getDisplayLanguage().toString());
        }
        String[] languages=(String[]) localcountries.toArray(new String[localcountries.size()]);
        Log.d(Arrays.asList(languages).contains("Kurdi")); //false
        Log.d(Arrays.asList(languages).contains("Kurdish")); //false
        Log.d(Arrays.asList(languages).contains("Persian")); //true
        // system info
        Log.d(getAndroidVersion()); // Android SDK: 28 (9)
}
 public String getAndroidVersion() {
        String release = Build.VERSION.RELEASE;
        int sdkVersion = Build.VERSION.SDK_INT;
        return "Android SDK: " + sdkVersion + " (" + release +")";
 }
```

**Comment by layik** [comment]
List of various issues reported. 
https://issuetracker.google.com/issues?q=kurdish

Sounds like this ticket is what we should be following up:
https://issuetracker.google.com/issues/37116299

**Comment by layik** [comment]
https://stackoverflow.com/q/57148759/11101153

Valuable answer:
https://stackoverflow.com/a/57162344/11101153

**Comment by layik** [comment]
Alright, I think we have a plan:

1. Locale must be done via ICU http://site.icu-project.org/bugs
2. So far don't know where we would then add keyboard layout(s)
3. Keyboard layout must be easy once (1) is done? Not sure. 


[Android](https://android.googlesource.com/?format=HTML) has two repos:
https://android.googlesource.com/platform/external/icu/
https://android.googlesource.com/platform/external/icu4c/
which are copies of the above I think
> This repo contains Android's copy of ICU4C and ICU4J and associated tools and code.

**Comment by layik** [comment]
Some twitter discussions especially heads up by Kak Jwtyar RE CLDR 
https://github.com/unicode-org/cldr/pulls?q=is%3Apr+is%3Aclosed+ckb
